### ISSUE TITLE
Pár mondatos összefoglalás a wiki-re

### ISSUE THREAD

**Issue by kiskovi97** [BME-MIT-IET/MaxPont-iet-2018#1]
A tárhely wikijének kezdőoldalára egy-két bekezdésben foglalja össze a csapat a saját szavaival, hogy mi a projekt célja, és nagyobb projekt esetén válasszon ki a funkcióknak egy részhalmazát, amivel később dolgozni fog majd.

**Comment by matemartyin** [comment]
A program egy XML-RDFS átalakító. Az XML-ben megadott sémákat (XSD) és adatokat képes átalakítani RDS vagy OWL-be. Erre a feladatra a már létező open source megoldások nem voltak megfelelőek, ezért a program készítője, a kereskedelmi forgalomban lévő programok kikerülésére, egy saját implementációt készített a problémára.

**Comment by kiskovi97** [comment]
Ez a program XML és XSD fájlok RDF/OWL formátumba való átalakítására képes. Fő osztálya az XSD2OWL?apper és a XML2OWLMapper, mely képes xsd és xml fájlokat beolvasni, átkonvertálni owl formátumba. az owl formátumot pedig kiíratni RDF/XML, RDF/XML-ABBREV, N-TRIPLE vagy N3 formátumba.

**Comment by dorog** [comment]
Az Ontmalizer képes mindenre kiterjedő átalakítást végezni. XMl sémából és XML adatokból képes automatikusan RDF/OWL-t létrehozni. Ez egy ingyenes eszköz. Nagyon komplesz sémákat nem képes kezelni, de ez nem is célja. Vannak még fizetős programok amik képesek
lennének azokat is kezelni.
XSD-ből RDF/OWL-ba: XSD2OWLMapper a fő osztály.
XML-ből RDF/OWL-ba: XML2OWLMapper a fő osztály.

**Comment by hemcraft** [comment]
Az Ontmalizer használható XML adatok és sémák RDF vagy OWL-be való átalakítására. XML sémák transzformálására XSD2OWLMapper osztályt lehet használni, XML adatok átalakítására pedig XML2OWLMappert. Kimeneti formátuma a kövektező lehet: RDF/XML, RDF/XML-ABBREV, N-TRIPLE és N3.

**Comment by kiskovi97** [comment]
Wiki-re az összegyűjtött összefoglalók alapján összeállítottam az összefoglalót.
