### ISSUE TITLE
CI és statikus ellenőrzés 01: Travis

### ISSUE THREAD

**Issue by kiskovi97** [BME-MIT-IET/MaxPont-iet-2018#2]
CI beüzemelése, ha még nincs (Travis)

**Comment by matemartyin** [comment]
A travis-t beüzemeltem, működik

**Comment by matemartyin** [comment]
A beüzemeléshez a travis-ci oldalán be kellett kapcsolni a repo-t, majd egy új commit-tal hozzáadni a .travis.yml fájlt. A commit-hoz tartozó commit: https://github.com/BME-MIT-IET/MaxPont-iet-2018/commit/3f582f5ac5bf0e51d074659b94f660f390984bbc

**Comment by kiskovi97** [comment]
A Travis sikeresen implementálva lett és le is futott hiba nélkül :)
