### ISSUE TITLE
Statikus analízis eszköz futtatása és jelzett hibák átnézése

### ISSUE THREAD

**Issue by kiskovi97** [BME-MIT-IET/MaxPont-iet-2018#4]
SonarQube beüzemelése a labor alapján

**Comment by hemcraft** [comment]
SonarQube telepítése sikeres, talált 1 bugot, 18 vulnerabilitest, és 61 code smellst, ezek átnézése folyamatban.

**Comment by dorog** [comment]
Minden jól működik, jól lett implementálva.
